### ISSUE TITLE
Toggle xiaomi relay is not working every time.

### ISSUE THREAD

**Issue by alextud** [andreypopov/node-red-contrib-deconz#82] opened 2020-06-21 12:08 UTC
** Describe issue **
When I toggle xiaomi relay (lumi.relay.c2acn01) on first run it's working. But on consecutive runs I get error logged below. After a while it is working again: one time then fails. When I replaced home-assistant control it's working every time.

** Your flow here **
<img width="503" alt="Screenshot 2020-06-21 at 15 04 49" src="https://user-images.githubusercontent.com/1692861/85224132-b8031280-b3d0-11ea-847a-f66e4d361c7d.png">
<img width="338" alt="Screenshot 2020-06-21 at 15 05 30" src="https://user-images.githubusercontent.com/1692861/85224134-bafe0300-b3d0-11ea-9087-ad77ed8a3586.png">

** Screens / Logs **
[error] [deconz-output:Toogle Kitchen strip] TypeError: Cannot use 'in' operator to search for 'on' in undefined
    at deConzOut.<anonymous> (/data/node_modules/node-red-contrib-deconz/nodes/out.js:100:121)
    at emitOne (events.js:116:13)
    at deConzOut.emit (events.js:211:7)
    at deConzOut.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)
    at InjectNode.Node.send (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:159:22)
    at InjectNode.<anonymous> (/usr/src/node-red/node_modules/@node-red/nodes/core/core/20-inject.js:78:26)
    at emitOne (events.js:116:13)
    at InjectNode.emit (events.js:211:7)
    at InjectNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)
    at /usr/src/node-red/node_modules/@node-red/nodes/core/core/20-inject.js:117:22

** Hardware / Software **
  - docker
  - version of deconz gateway: [2.05.78 / 22/05/2020] 
  - version of node-red-contrib-deconz: [1.1.14]

**Comment by jasimancas** [comment] 2020-07-01 17:55
Same error here

**Comment by andreypopov** [comment] 2020-07-01 17:57
did u try 1.1.15 ?

**Comment by andreypopov** [comment] 2020-07-01 18:00
Please, add error log from 1.1.15

**Comment by jasimancas** [comment] 2020-07-01 18:14
1.1.15


1 Jul 19:32:33 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
1 Jul 19:32:28 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
1 Jul 19:32:30 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
1 Jul 19:32:44 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
1 Jul 19:32:51 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
1 Jul 19:32:53 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined

**Comment by jasimancas** [comment] 2020-07-02 19:26
More....

2 Jul 12:47:53 - [error] [deconz-get:Estado Entrada] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 12:53:01 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 12:53:02 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 12:53:03 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 12:53:04 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 12:53:07 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 14:38:35 - [error] [deconz-get:Estado Pasillo] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 15:35:40 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined,
2 Jul 15:35:43 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'reachable' in undefined

**Comment by andreypopov** [comment] 2020-07-03 06:56
try 1.1.16

**Comment by jasimancas** [comment] 2020-07-03 08:33
Updated, I will try a few days to see if the error is repeated.

**Comment by StephanStS** [comment] 2020-07-03 14:57
Similar at my setup:
I readout the brightness of an Philips Hue Adore bath lamp every 3 seconds. 

Very often I am not able to select the bri (for brightness) as payload value:
![grafik](https://user-images.githubusercontent.com/57687516/86479759-10310180-bd4d-11ea-89bf-480a6b5bda55.png)

It seems that 1.1.16 is worse in this behaviour compared to 1.1.14 and 1.1.15.
Is there any log or example flow I could post here for a better examination?

**Comment by jasimancas** [comment] 2020-07-04 14:48
1.1.16 and the error again..


4 Jul 16:45:24 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'on' in undefined,
4 Jul 16:45:35 - [error] [deconz-get:Estado Dormitorio] TypeError: Cannot use 'in' operator to search for 'on' in undefined

**Comment by amaximchuk** [comment] 2020-07-06 23:30
I have the same issue on 1.1.16

**Comment by Toutipois** [comment] 2020-07-10 06:58
I have the same issue with ikea bulbs in some cases.
I've facing this issue since I updated  node-red to 1.1.0 and deconz 1.1.16.

I noticed that the error comes when flows are using:
- **Get** node 
- **Output** node with  **Toggle** command

I downgraded node-red et deconz to the previous versions used but the error is still present..

Did you guys find what's wrong ?

Let me know if want more informations.

**Comment by andreypopov** [comment] 2020-07-10 07:25
I will check this issue in this weekend
what is server node polling time ?

**Comment by Toutipois** [comment] 2020-07-10 08:25
Andrey,

Find below more infomations: 

- Raspberry pi 4 Raspbian GNU/Linux 10 (buster)
- Node v12.18.2   Npm 6.14.5
- Node red 1.1.1 / deconz 1.1.16
- Conbee II - Firmware 26580700

I'm not sure about what you are asking for.

**Comment by StephanStS** [comment] 2020-07-10 10:34
I am polling every 3 seconds via the Get node.

My system:
- Raspberry Pi 2B running Buster
- Node red 1.1.1,  deconz 1.1.16
- Conbee II - Firmware 26580700
- Firmware version 2.05.78

**Comment by andreypopov** [comment] 2020-07-10 10:35
> I am polling every 3 seconds via the Get node.
> 
> My system:
> 
> * Raspberry Pi 2B running Buster
> * Node red 1.1.1,  deconz 1.1.16
> * Conbee II - Firmware 26580700
> * Firmware version 2.05.78

please, set to default 15sec and test again

**Comment by Toutipois** [comment] 2020-07-10 13:02
My pooling parameter is set at 15 sec (never change it) and the issue is present.

**Comment by andreypopov** [comment] 2020-07-12 13:07
There were changes in API! 
i fixed toggle, please check

**Comment by Toutipois** [comment] 2020-07-12 13:34
I've just done a quick test.

Toggle fonction and get node do not report error anymore. 
Everything seems to work fine.

Thanks for your job.

**Comment by StephanStS** [comment] 2020-07-12 16:14
Same for me. With updating to  deconz v 1.2.0 all is working fine. Tested on two Node-RED instances running on two different Raspberry Pi devices.
Thx.

I propose to close this issue.

**Closed** 2020-07-12 17:45 UTC
Labels: bug
