### ISSUE TITLE
Reboot Node-red after add node

### ISSUE THREAD

**Issue by arozhankov** [andreypopov/node-red-contrib-deconz#42] opened 2019-11-25 10:06 UTC
** Describe issue **
When adding a new deconz-in or deconz-out node or after deleting them after deploying immediately or after accessing to nodes (deconz-in or deconz-out), node red is reboot...

** Hardware / Software **
  - raspbian for node-red (windows for conbee)
  - version of deconz gateway: [2.05.69 / 07/09/2019] 
  - version of node-red-contrib-deconz: [1.0.4]

**Comment by andreypopov** [comment] 2019-11-26 06:21
1.0.4 is too old. Please, install the latest version.
In case of error, write node-red log here.

![2019-11-26_09-14-56](https://user-images.githubusercontent.com/1624839/69604234-e5036880-102d-11ea-9ddf-c4d32dc29543.png)

**Comment by arozhankov** [comment] 2019-12-15 04:12
Hello.
Sorry for delay.

Now i have.
1. New OS
2. Freshly installed Node-red 1.0.3
3. Deconz 1.1.9

The error was repeated.

There are two options:
1. node-red fails (see the log below - this happened after deleting the in or out node - I deleted some at once).
2. The interface for configuring nodes from the deconz palette is destroyed (fields and parameters are displayed incorrectly)

==========
`ERROR: cant get 52fa3504.3625dc node, removed from list
15 Dec 10:53:04 - [red] Uncaught Exception:
15 Dec 10:53:04 - TypeError: Cannot read property 'devices' of null
    at ServerNode.onSocketMessage (C:\Users\al\.node-red\node_modules\node-red-contrib-deconz\nodes\server.js:237:37)
    at DeconzSocket.<anonymous> (C:\Users\al\.node-red\node_modules\node-red-contrib-deconz\nodes\server.js:34:57)
    at DeconzSocket.emit (events.js:210:5)
    at DeconzSocket.onMessage (C:\Users\al\.node-red\node_modules\node-red-contrib-deconz\lib\deconz-socket.js:137:18)
    at WebSocket.<anonymous> (C:\Users\al\.node-red\node_modules\node-red-contrib-deconz\lib\deconz-socket.js:59:48)
    at WebSocket.emit (events.js:210:5)
    at Receiver.receiverOnMessage (C:\Users\al\.node-red\node_modules\ws\lib\websocket.js:800:20)
    at Receiver.emit (events.js:210:5)
    at Receiver.dataMessage (C:\Users\al\.node-red\node_modules\ws\lib\receiver.js:423:14)
    at Receiver.getData (C:\Users\al\.node-red\node_modules\ws\lib\receiver.js:353:17)
    at Receiver.startLoop (C:\Users\al\.node-red\node_modules\ws\lib\receiver.js:139:22)
    at Receiver._write (C:\Users\al\.node-red\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Receiver.Writable.write (_stream_writable.js:305:11)
    at Socket.socketOnData (C:\Users\al\.node-red\node_modules\ws\lib\websocket.js:875:35)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)`

**Comment by akoivist** [comment] 2020-01-08 17:05
Hello,

I'm not 100% sure I understand the code fully, but should line 237 of server.js:
`delete node.devices[nodeId];`
be
`delete this.devices[nodeId];` ?

#49 is probably a duplicate of this?

But what is the situation with deconz where this line is executed? It does not occur even once a month.

**Comment by andreypopov** [comment] 2020-01-08 18:27
hm. looks like that should be:
**delete that.devices[nodeId];**

It is rare case

**Comment by andreypopov** [comment] 2020-01-08 18:33
+ node-red-contrib-deconz@1.1.10

thanks!

**Closed** 2020-01-13 11:30 UTC
Labels: bug

**Comment by akoivist** [comment] 2020-01-13 21:00
Thank you, but the problem moved to the next line
`if ("server" in node) {`
which now throws the same null error, because 'node' is undefined in that else-branch.
